### ISSUE TITLE
32bit apps don't work while jailbroken 

### ISSUE THREAD

**Issue by Zeebins** [PsychoTea/MeridianJB#38]
All 32bit apps immediately crash wile jailbroken. They do open while in safe mode though. Seems to be due to Tweak loader. I've copied a crash report from CrashReporter. 
https://ghostbin.com/paste/wtyec

**Comment by sbingner** [comment]
That should mean you have a tweak that doesn't work right on 32bit.  Anemone doesn't and was explicitly blacklisted until updated as a result but he can't go through and blacklist every bad tweak.  Remove your tweaks then reinstall them until it starts happening again and you'll know where your problem is.
